name: Build Godot APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build APK
        uses: dulvui/godot-android-export@v2
        with:
          godot-version: '4.4'
          working-directory: '.'
          keystore-base64: ${{ secrets.KEYSTORE }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          keystore-alias: ${{ secrets.KEYSTORE_ALIAS }}
          keystore-alias-password: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: game-apk
          path: '*.apk'
